color a
adb uninstall com.android.bluetoothmidiservice
adb uninstall com.android.callogbackup
adb uninstall com.android.chrome
adb uninstall com.android.dreams.photoable
adb uninstall com.android.mediacenter
adb uninstall com.android.providers.partnerbookmarks
adb uninstall com.facebook.appmanager
adb uninstall com.facebook.services
adb uninstall com.facebook.system
adb uninstall com.google.android.apps.docs
adb uninstall com.google.android.apps.maps
adb uninstall com.google.android.apps.messaging
adb uninstall com.google.android.apps.photos
adb uninstall com.google.android.apps.restore
adb uninstall com.google.android.app.tachyon
adb uninstall com.google.android.feedback
adb uninstall com.google.android.gm
adb uninstall com.google.android.googlequicksearchbox
adb uninstall com.google.android.marvin.talkback
adb uninstall com.google.android.music
adb uninstall com.google.android.onetimeinitializer
adb uninstall com.google.android.partnersetup
adb uninstall com.google.android.printservice.recommendation
adb uninstall com.google.android.videos
adb uninstall com.google.android.youtube
adb uninstall com.huawei.android.chr
adb uninstall com.huawei.android.hsf
adb uninstall com.huawei.android.pushagent
adb uninstall com.huawei.android.wfdft
adb uninstall com.huawei.bluetooth
adb uninstall com.huawei.contacts.sync
adb uninstall com.huawei.hicloud
adb uninstall com.huawei.hifolder
adb uninstall com.huawei.himovie.overseas
adb uninstall com.huawei.hiviewtunnel
adb uninstall com.huawei.hwdetectrepair
adb uninstall com.huawei.hwid
adb uninstall com.huawei.HwMultiScreenShot
adb uninstall com.huawei.iaware
adb uninstall com.huawei.phoneservice
adb uninstall com.huawei.powergenie
adb uninstall com.huawei.trustagent
adb uninstall com.mediatek.wfo.impl
adb uninstall com.swiftkey.swiftkeyconfigurator
adb uninstall com.android.documentsui
adb uninstall com.android.calendar
adb uninstall com.android.emergency
adb uninstall com.huawei.hidisk
adb uninstall com.android.proxyhandler
adb uninstall com.android.deskclock
adb uninstall com.android.contacts
adb uninstall com.android.bookmarkprovider
adb uninstall com.android.email
adb uninstall com.android.gallery3d
adb uninstall com.android.providers.calendar
adb uninstall com.android.providers.contacts
adb uninstall com.android.providers.downloads
adb uninstall com.android.providers.downloads.ui
adb uninstall com.android.vending
adb uninstall com.android.wallpaper.livepicker
adb uninstall com.android.wallpaperbackup
adb uninstall com.android.wallpapercropper
adb uninstall com.example.android.notepad
adb uninstall com.google.android.syncadapters.calendar 
adb uninstall com.google.android.setupwizard
adb uninstall com.huawei.android.internal.app
adb uninstall com.huawei.android.thememanager
adb uninstall com.huawei.android.launcher
adb uninstall com.huawei.appmarket
adb uninstall com.huawei.camera
adb uninstall com.huawei.KoBackup
adb uninstall com.huawei.printservice
adb uninstall com.huawei.screenrecorder
adb uninstall com.touchtype.swiftkey
adb uninstall com.android.printspooler
adb uninstall com.huawei.securitymgr
adb uninstall com.android.incallui
